-- ============================================================
-- SQL Sales Exploratory Data Analysis (PostgreSQL)
-- Tables used: customers, products, sales
-- ============================================================

-- ==================== Database Exploration ====================

-- Explore table metadata.
SELECT *
FROM information_schema.tables;

-- Explore columns in the customers table.
SELECT *
FROM information_schema.columns
WHERE table_name = 'customers';

-- ==================== Dimension Exploration ====================

-- Explore all countries customers come from.
SELECT DISTINCT country AS "Country"
FROM customers;

-- Explore product divisions and product names.
SELECT DISTINCT category, subcategory, product_name
FROM products
ORDER BY 1, 2, 3;

-- ==================== Date Exploration ====================

-- Find the first and last order dates, and years of available sales.
SELECT
    MIN(order_date) AS first_order_date,
    MAX(order_date) AS last_order_date,
    EXTRACT(YEAR FROM AGE(MAX(order_date), MIN(order_date))) || ' years' AS years
FROM sales;

-- Find the youngest and oldest customer.
SELECT
    MAX(birthdate) AS youngest_birthdate,
    EXTRACT(YEAR FROM AGE(MAX(birthdate))) || ' years' AS youngest_customer_age,
    MIN(birthdate) AS oldest_birthdate,
    EXTRACT(YEAR FROM AGE(MIN(birthdate))) || ' years' AS oldest_customer_age
FROM customers;

-- ==================== Measure Exploration ====================

-- Total sales.
SELECT SUM(sales_amount) AS total_sales
FROM sales;

-- Total items sold.
SELECT SUM(quantity) AS total_items_sold
FROM sales;

-- Average selling price.
SELECT ROUND(AVG(price), 2) AS average_price
FROM sales;

-- Total distinct orders.
SELECT COUNT(DISTINCT order_number) AS total_orders
FROM sales;

-- Total products.
SELECT COUNT(DISTINCT product_id) AS total_products
FROM products;

-- Total customers.
SELECT COUNT(DISTINCT customer_id) AS total_customers
FROM customers;

-- Customers who placed an order.
SELECT COUNT(DISTINCT customer_key) AS customers_with_orders
FROM sales;

-- Business KPI report.
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value
FROM sales
UNION ALL
SELECT 'Total Quantity Sold', SUM(quantity)
FROM sales
UNION ALL
SELECT 'Average Price', ROUND(AVG(price), 2)
FROM sales
UNION ALL
SELECT 'Total Number of Orders', COUNT(DISTINCT order_number)
FROM sales
UNION ALL
SELECT 'Total Number of Products', COUNT(DISTINCT product_key)
FROM products
UNION ALL
SELECT 'Total Number of Customers', COUNT(DISTINCT customer_id)
FROM customers;

-- ==================== Magnitude Exploration ====================

-- Total customers by country.
SELECT country, COUNT(customer_id) AS total_customers
FROM customers
GROUP BY country
ORDER BY total_customers DESC;

-- Total customers by gender.
SELECT gender, COUNT(customer_key) AS total_customers
FROM customers
GROUP BY gender;

-- Total products by category.
SELECT category, COUNT(product_key) AS total_products
FROM products
GROUP BY category
ORDER BY total_products DESC;

-- Average cost by category.
SELECT category, ROUND(AVG(cost), 2) AS average_cost
FROM products
GROUP BY category
ORDER BY average_cost DESC;

-- Total revenue by category.
SELECT
    p.category,
    COALESCE(SUM(s.sales_amount), 0) AS total_revenue
FROM products AS p
LEFT JOIN sales AS s
    ON p.product_key = s.product_key
WHERE p.category IS NOT NULL
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Revenue generated by each customer.
SELECT
    c.customer_key,
    c.first_name || ' ' || c.last_name AS customer,
    COALESCE(SUM(s.sales_amount), 0) AS total_revenue
FROM customers AS c
LEFT JOIN sales AS s
    ON c.customer_key = s.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC;

-- Distribution of sold items by country.
SELECT
    c.country,
    COALESCE(SUM(s.quantity), 0) AS items_sold
FROM customers AS c
LEFT JOIN sales AS s
    ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY items_sold DESC;

-- ==================== Ranking Analysis ====================

-- Top five products by revenue.
SELECT
    p.product_name,
    COALESCE(SUM(s.sales_amount), 0) AS revenue
FROM products AS p
LEFT JOIN sales AS s
    ON p.product_key = s.product_key
GROUP BY p.product_name
ORDER BY revenue DESC
LIMIT 5;

-- Five lowest-performing products by revenue.
SELECT
    p.product_name,
    COALESCE(SUM(s.sales_amount), 0) AS revenue
FROM products AS p
LEFT JOIN sales AS s
    ON p.product_key = s.product_key
GROUP BY p.product_name
ORDER BY revenue ASC
LIMIT 5;

-- Top ten customers by revenue.
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    COALESCE(SUM(s.sales_amount), 0) AS revenue
FROM customers AS c
LEFT JOIN sales AS s
    ON c.customer_key = s.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY revenue DESC
LIMIT 10;

-- Three customers with the fewest orders.
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT s.order_number) AS total_orders
FROM customers AS c
LEFT JOIN sales AS s
    ON c.customer_key = s.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_orders ASC
LIMIT 3;
